### ISSUE TITLE
Inital impl

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/installer-action#1]
Am besten einfach via curl das release in den installer laden

https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/install/lib/api_package_upload.php#L52

https://github.com/yakamara/redaxoorg/blob/master/src/addons/project/lib/Webservice/Packages.php#L149-L272

https://github.com/sdras/awesome-actions

**Comment by staabm** [comment]
Ggf zur Orientierung 
https://github.com/skx/github-action-publish-binaries

**Comment by gharlan** [comment]
Der Api-Key von redaxo.org lässt sich so hinterlegen: https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables

**Comment by gharlan** [comment]
`POST https://www.redaxo.org/de/ws/packages?package=<key>&file_id=0`

Multipart mit Post-Fields:
`version=<version>&redaxo_versions[]=5.x&description=<description>&status=1&checksum=<md5-checksum>`

Plus Datei-Upload als `archive`

**Comment by bloep** [comment]
Erstes release ist erstellt :tada:
