### ISSUE TITLE
Addon-Key definieren können

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/installer-action#20]
Gibt es die Möglichkeit, den Addon-Key abweichend vom Repository-Namen zu definieren?

**Comment by gharlan** [comment]
Wenn ich das richtig sehe, liest die Action den Package-Namen aus der package.yml aus:
https://github.com/FriendsOfREDAXO/installer-action/blob/a66431a357f0d8f20ffe6bdba6d3c1c9f1dd12fa/src/index.ts#L14

**Comment by alxndr-w** [comment]
Noch besser!
