### ISSUE TITLE
Installer-Action auf GitHub offiziell veröffentlichen?

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/installer-action#22]
https://github.com/FriendsOfREDAXO/installer-action/releases/new?marketplace=true

**Comment by bloep** [comment]
Danke für den Vorschlag.

Ich hatte darüber auch schon nachgedacht, wollte mir vorher noch die `GitHub Marketplace Developer Agreement v2.3` in Ruhe durchlesen.

**Comment by bloep** [comment]
https://github.com/marketplace/actions/myredaxo-installer-action
