### ISSUE TITLE
Release Tag und Version in package.yml vergleichen

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/installer-action#222]
Ich fände es hilfreich, wenn die Action überprüfen würde, ob die Version in der package.yml und der Version-Tag in Github identisch sind bevor ein Release erstellt wird.
Das würde verhindern, dass man aus versehen eine Version released, aber vergessen hat die package.yml anzupassen.

**Comment by alxndr-w** [comment]
Das scheint bereits der Fall zu sein.
