### ISSUE TITLE
dot-Files werden ignoriert

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/installer-action#9]
Beim zip werden dot-Dateien ignoriert. 
Dadurch geht bei yrewrite die .htaccess Datei verloren (https://github.com/yakamara/redaxo_yrewrite/issues/454).
Generell können diese Dateien mit einer Option eingebunden werden `archive.glob('**', {cwd: './dir', skip: [], ignore: [], dot: true}, {prefix: 'test'})` das funktioniert natürlich nicht, wegen den .gitignore und co.
Vielleicht kann man neben 'installer_ignore' noch so etwas wie 'installer_include' anbieten um Dateien einzeln zu laden `archive.file('./dir/setup/.htaccess', { name: 'setup/.htaccess' });`.

**Comment by alxndr-w** [comment]
Alternativ die Ursprungsdatei umbenennen und beim kopieren wieder richtig benennen. Es wird in den seltensten Fällen ein dot-File benötigt.

**Comment by bloep** [comment]
> Alternativ die Ursprungsdatei umbenennen und beim kopieren wieder richtig benennen. Es wird in den seltensten Fällen ein dot-File benötigt.

das stimmt wohl. Mein Ziel ist jedoch, dass die GA den gleichen ZIP-Inhalt erzeugt, wie es das REDAXO Backend macht.

**Comment by eaCe** [comment]
Umbenennen und verschieben kommt mir etwas '
schmutziger' vor, funktioniert aber natürlich auch. Man muss das eben nur wissen, ist aktuell auch nur bei yrewrite problematisch.

**Comment by alxndr-w** [comment]
@eaCe ist jetzt akademisch, aber da die mitgelieferte `.htaccess` ja beim Installieren des Addons auch noch nicht an der richtigen Stelle ist (root), könnte sie ja schon `default.htaccess` im Addon-Verzeichnis bei der Auslieferung heißen, o.ä.

**Comment by eaCe** [comment]
@alxndr-w das ist korrekt, was würde aber denn gegen ein include sprechen? Dann wäre die Logik zwischen in- und exclude die gleiche. Aber wie gesagt, das kopieren ist mir relativ egal. 
Ich finde es nur nicht gut alle .-Dateien einzubnden.
